### ISSUE TITLE
btrfs-space-calculator device size is not optional

### ISSUE THREAD

**Issue by arvidjaar** [knorrie/python-btrfs#20]
Help output makes impression device sizes can be omitted. They cannot (or is there usage where they can?).

```
bor@bor-Latitude-E5450:~/src/python-btrfs$ git describe HEAD
v11
bor@bor-Latitude-E5450:~/src/python-btrfs$ ./bin/btrfs-space-calculator -h
usage: btrfs-space-calculator [-h] -m METADATA -d DATA [-M] [-r RATIO]
                              [sizes [sizes ...]]
...
bor@bor-Latitude-E5450:~/src/python-btrfs$ ./bin/btrfs-space-calculator -m single -d single
Traceback (most recent call last):
  File "./bin/btrfs-space-calculator", line 189, in <module>
    main()
  File "./bin/btrfs-space-calculator", line 158, in main
    usage = btrfs.fs_usage.FsUsage(fs)
  File "/home/bor/src/python-btrfs/bin/btrfs/fs_usage.py", line 520, in __init__
    self._simulate_chunk_allocations(device_sizes)
  File "/home/bor/src/python-btrfs/bin/btrfs/fs_usage.py", line 675, in _simulate_chunk_allocations
    ratio = self._data_metadata_ratio()
  File "/home/bor/src/python-btrfs/bin/btrfs/fs_usage.py", line 603, in _data_metadata_ratio
    used_fraction = self.virtual_used / self.total
ZeroDivisionError: division by zero
bor@bor-Latitude-E5450:~/src/python-btrfs$ 
```

**Comment by knorrie** [comment]
Yes, this is incorrect indeed. Thanks for the report.
