### ISSUE TITLE
struct.error: unpack_from requires a buffer of at least 12 bytes

### ISSUE THREAD

**Issue by knorrie** [knorrie/python-btrfs#3]
Uhoh...

```
./show_block_group_contents.py 155713536000 /
[...]
extent vaddr 156097769472 length 16384 refs 3 gen 35254 flags DATA
    extent data backref root 257 objectid 150469 offset 0 count 1
    shared data backref parent 183848517632 count 1
    shared data backref parent 33333886976 count 1
extent vaddr 156109320192 length 4096 refs 9 gen 34379 flags DATA
    extent data backref root 319 objectid 574623 offset 6778880 count 1
    shared data backref parent 184193253376 count 1
    shared data backref parent 183844847616 count 1
    shared data backref parent 183840768000 count 1
    shared data backref parent 34028601344 count 1
    shared data backref parent 33983873024 count 1
    shared data backref parent 33752367104 count 1
    shared data backref parent 33468841984 count 1
    shared data backref parent 33417953280 count 1
extent vaddr 156109971456 length 4096 refs 1 gen 34379 flags DATA
    extent data backref root 319 objectid 574623 offset 4620288 count 1
extent vaddr 156111749120 length 4096 refs 1 gen 34383 flags DATA
    shared data backref parent 638205952 count 1
Traceback (most recent call last):
  File "../python-btrfs/examples/show_block_group_contents.py", line 11, in <module>
    for extent in fs.extents(vaddr, vaddr + block_group.length - 1):
  File "/home/knorrie/src/git/python-btrfs/examples/btrfs/ctree.py", line 381, in extents
    extent.append_shared_data_ref(header, data)
  File "/home/knorrie/src/git/python-btrfs/examples/btrfs/ctree.py", line 535, in append_shared_data_ref
    self.shared_data_refs.append(SharedDataRef(data, 0))
  File "/home/knorrie/src/git/python-btrfs/examples/btrfs/ctree.py", line 559, in __init__
    self.parent, self.count = SharedDataRef.shared_data_ref.unpack_from(data, pos)
struct.error: unpack_from requires a buffer of at least 12 bytes
```

**Comment by knorrie** [comment]
Fixed in b1142702080aab0287963efa0c5131964a8f9028
